use_frameworks!

platform :ios, '9.0'

target 'LSJHNoticeBar_Example' do
  pod 'LSJHNoticeBar', :path => '../'

  target 'LSJHNoticeBar_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
